import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Component } from "react";
import { AppProps } from "next/app";
// import { Session } from "next-auth";
// import { SessionProvider } from "next-auth/react";
// import { NextAuthProvider } from "./providers";
import { getCurrentScheme } from "@/utils/colorScheme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const scheme = await getCurrentScheme();
  return (
    <html lang="en" className={scheme === "dark" ? "dark" : ""}>
      <body className={inter.className}>
        {children}
        {/* <NextAuthProvider>{children}</NextAuthProvider> */}
      </body>
    </html>
  );
}
